<?php
function setSessioniExpiry() {
  $cookie = $_COOKIE[session_id()];
  $_SESSION['cookieExpires'] = time() + 1800;
  setCookie(session_id(), $cookie, time() + 1800);
}

function session_management_init() {
  $cookieExpiry = ini_get('session.cookie_lifetime');
  $sessionExpiry = ini_get('session.gc_maxlifetime');
  if (!empty($_SESSION)) {
    if(!isset($_SESSION['expires'])) {
      $_SESSION['expires']  = time() + $sessionExpiry;
      $_SESSION['cookieExpires'] = time() + $cookieExpiry;
    }

    //calculate session time remaining
    $_SESSION['timeLeft'] = $_SESSION['expires'] - time();
    $_SESSION['refreshLength'] = $cookieExpiry;
    
    //Extend the cookie time by 30 minutes if cookie time has not passed
    if (isset($_SESSION['cookieExpires'])) {
      if($_SESSION['cookieExpires'] > time()) {
        setSessioniExpiry();
      }
      else {
        session_destroy();
      }
    }
    else {
      setSessioniExpiry();
    }
  }
}
