<?php
/**
 * @file
 * article_content_type.features.uuid_term.inc
 */

/**
 * Implements hook_uuid_features_default_terms().
 */
function article_content_type_uuid_features_default_terms() {
  $terms = array();

  $terms[] = array(
    'name' => 'Fleet',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '02369248-dfde-43f2-a717-44b6e29364f6',
    'vocabulary_machine_name' => 'portfolio',
    'url_alias' => array(
      0 => array(
        'alias' => 'portfolio/fleet',
        'language' => 'und',
      ),
    ),
  );
  $terms[] = array(
    'name' => 'Unified Records Management',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '0282781c-096c-4fc1-9ef5-a074a65fad46',
    'vocabulary_machine_name' => 'portfolio',
    'url_alias' => array(
      0 => array(
        'alias' => 'portfolio/unified-records-management',
        'language' => 'und',
      ),
    ),
  );
  $terms[] = array(
    'name' => 'cloud',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '06752c7c-e85d-4c7a-9987-4bd0bf62fad0',
    'vocabulary_machine_name' => 'tags',
    'url_alias' => array(
      0 => array(
        'alias' => 'tags/cloud',
        'language' => 'und',
      ),
    ),
  );
  $terms[] = array(
    'name' => 'Domestic Delivery Services',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '0acb55d1-c876-4c8c-8154-ad16b94909d1',
    'vocabulary_machine_name' => 'portfolio',
    'url_alias' => array(
      0 => array(
        'alias' => 'portfolio/domestic-delivery-services',
        'language' => 'und',
      ),
    ),
  );
  $terms[] = array(
    'name' => 'Police',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '0d393850-bc87-48c9-95cc-da4b69dd6fb8',
    'vocabulary_machine_name' => 'portfolio',
    'url_alias' => array(
      0 => array(
        'alias' => 'portfolio/police',
        'language' => 'und',
      ),
    ),
  );
  $terms[] = array(
    'name' => 'Workplace Reconfiguration',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '0f48c1cc-06b2-4387-aca3-3ca2cf7ee1e5',
    'vocabulary_machine_name' => 'portfolio',
    'url_alias' => array(
      0 => array(
        'alias' => 'portfolio/workplace-reconfiguration',
        'language' => 'und',
      ),
    ),
  );
  $terms[] = array(
    'name' => 'Household Goods Shipping',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '13b8180c-cbf5-4eab-a65f-4360df2bf8d6',
    'vocabulary_machine_name' => 'portfolio',
    'url_alias' => array(
      0 => array(
        'alias' => 'portfolio/household-goods-shipping',
        'language' => 'und',
      ),
    ),
  );
  $terms[] = array(
    'name' => 'Data Center',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '149460ac-7b7b-460c-88e4-cb1d5e540758',
    'vocabulary_machine_name' => 'portfolio',
    'url_alias' => array(
      0 => array(
        'alias' => 'portfolio/data-center',
        'language' => 'und',
      ),
    ),
  );
  $terms[] = array(
    'name' => 'IAAS/PAAS Managed IT',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '1bd08cdc-95d6-48d3-b1e8-bf59c9f87779',
    'vocabulary_machine_name' => 'portfolio',
    'url_alias' => array(
      0 => array(
        'alias' => 'portfolio/iaaspaas-managed-it',
        'language' => 'und',
      ),
    ),
  );
  $terms[] = array(
    'name' => 'Servers',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '1d39efa7-6702-41fa-b0c5-514e03217b54',
    'vocabulary_machine_name' => 'portfolio',
    'url_alias' => array(
      0 => array(
        'alias' => 'portfolio/servers',
        'language' => 'und',
      ),
    ),
  );
  $terms[] = array(
    'name' => 'Advisory Services',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '1d648485-1098-4fa9-83cd-3e161950a2da',
    'vocabulary_machine_name' => 'portfolio',
    'url_alias' => array(
      0 => array(
        'alias' => 'portfolio/advisory-services',
        'language' => 'und',
      ),
    ),
  );
  $terms[] = array(
    'name' => 'Federal Public Key Infrastructure (FPKI)',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '1fe47f6e-9eaa-4af2-aade-9fc6b41e585e',
    'vocabulary_machine_name' => 'portfolio',
    'url_alias' => array(
      0 => array(
        'alias' => 'portfolio/federal-public-key-infrastructure-fpki',
        'language' => 'und',
      ),
    ),
  );
  $terms[] = array(
    'name' => 'Audio/Visual Equipment',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '27b5fff0-5993-4c0c-9422-0b5db9ebab54',
    'vocabulary_machine_name' => 'portfolio',
    'url_alias' => array(
      0 => array(
        'alias' => 'portfolio/audiovisual-equipment',
        'language' => 'und',
      ),
    ),
  );
  $terms[] = array(
    'name' => 'Courier Services',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '2842cff1-3919-4482-aeaa-aa0d0f3fc9c6',
    'vocabulary_machine_name' => 'portfolio',
    'url_alias' => array(
      0 => array(
        'alias' => 'portfolio/courier-services',
        'language' => 'und',
      ),
    ),
  );
  $terms[] = array(
    'name' => 'Travel Management Information Service',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '285f478f-a852-4e11-a6cc-9132630e687a',
    'vocabulary_machine_name' => 'portfolio',
    'url_alias' => array(
      0 => array(
        'alias' => 'portfolio/travel-management-information-service',
        'language' => 'und',
      ),
    ),
  );
  $terms[] = array(
    'name' => 'human resources',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '2a969665-24f7-43e1-bb7e-4cde89c0ce1d',
    'vocabulary_machine_name' => 'tags',
    'url_alias' => array(
      0 => array(
        'alias' => 'tags/human-resources',
        'language' => 'und',
      ),
    ),
  );
  $terms[] = array(
    'name' => 'Automotive Services',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '2d4c2f64-1670-4e5e-9517-39e933a6979b',
    'vocabulary_machine_name' => 'portfolio',
    'url_alias' => array(
      0 => array(
        'alias' => 'portfolio/automotive-services',
        'language' => 'und',
      ),
    ),
  );
  $terms[] = array(
    'name' => 'Engineering & Environmental Services',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '32722425-a32d-47f7-a632-0351e9ad1f25',
    'vocabulary_machine_name' => 'portfolio',
    'url_alias' => array(
      0 => array(
        'alias' => 'portfolio/engineering-environmental-services',
        'language' => 'und',
      ),
    ),
  );
  $terms[] = array(
    'name' => 'Home Sale Services',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '3354cd0b-a530-4ece-a515-ac360abe1007',
    'vocabulary_machine_name' => 'portfolio',
    'url_alias' => array(
      0 => array(
        'alias' => 'portfolio/home-sale-services',
        'language' => 'und',
      ),
    ),
  );
  $terms[] = array(
    'name' => 'Managed Print Services',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '34c457f2-16e0-4b6c-aa5c-c8c9fb67bf11',
    'vocabulary_machine_name' => 'portfolio',
    'url_alias' => array(
      0 => array(
        'alias' => 'portfolio/managed-print-services',
        'language' => 'und',
      ),
    ),
  );
  $terms[] = array(
    'name' => 'Human Resources and Training Services',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => '377dbb68-8db4-44b4-b43b-65825331d5d7',
    'vocabulary_machine_name' => 'portfolio',
    'url_alias' => array(
      0 => array(
        'alias' => 'portfolio/human-resources-and-training-services-0',
        'language' => 'und',
      ),
    ),
  );
  $terms[] = array(
    'name' => 'Managed Security Services',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '37fddf57-31cd-4b15-b660-9e3cd44d9730',
    'vocabulary_machine_name' => 'portfolio',
    'url_alias' => array(
      0 => array(
        'alias' => 'portfolio/managed-security-services',
        'language' => 'und',
      ),
    ),
  );
  $terms[] = array(
    'name' => 'Air Travel',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '394e5fd4-c550-4c69-818e-46d808c9c53c',
    'vocabulary_machine_name' => 'portfolio',
    'url_alias' => array(
      0 => array(
        'alias' => 'portfolio/air-travel',
        'language' => 'und',
      ),
    ),
  );
  $terms[] = array(
    'name' => 'Emerging Technologies And Services',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '3ac2ceba-2f2f-4d9f-bb4b-30d9b72e5ac2',
    'vocabulary_machine_name' => 'portfolio',
    'url_alias' => array(
      0 => array(
        'alias' => 'portfolio/emerging-technologies-and-services',
        'language' => 'und',
      ),
    ),
  );
  $terms[] = array(
    'name' => 'Window Treatment',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '3b67c851-3a75-4b03-80ef-478e9b06b26a',
    'vocabulary_machine_name' => 'portfolio',
    'url_alias' => array(
      0 => array(
        'alias' => 'portfolio/window-treatment',
        'language' => 'und',
      ),
    ),
  );
  $terms[] = array(
    'name' => 'Development',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '3e7ad049-c22d-45f3-9f1c-1f3174654221',
    'vocabulary_machine_name' => 'tags',
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'Development',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '41173314-c6b6-44a2-bd09-27a857ed19fc',
    'vocabulary_machine_name' => 'portfolio',
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'Infrastructure Software',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '4929362b-7644-4311-aa95-4df67de4958a',
    'vocabulary_machine_name' => 'portfolio',
    'url_alias' => array(
      0 => array(
        'alias' => 'portfolio/infrastructure-software',
        'language' => 'und',
      ),
    ),
  );
  $terms[] = array(
    'name' => 'Satellite Services',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '4bea195e-44ce-4099-aaff-68a63c664374',
    'vocabulary_machine_name' => 'portfolio',
    'url_alias' => array(
      0 => array(
        'alias' => 'portfolio/satellite-services',
        'language' => 'und',
      ),
    ),
  );
  $terms[] = array(
    'name' => 'Learn',
    'description' => '<p>Description of&nbsp;Learn.</p>
',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '56a96240-9032-4c0c-9339-20ef2f12d755',
    'vocabulary_machine_name' => 'interaction_mode',
    'url_alias' => array(
      0 => array(
        'alias' => 'interaction-mode/learn',
        'language' => 'und',
      ),
    ),
  );
  $terms[] = array(
    'name' => 'Peripherals',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '56bbf79a-8080-4a8b-b1a7-07c5416047b1',
    'vocabulary_machine_name' => 'portfolio',
    'url_alias' => array(
      0 => array(
        'alias' => 'portfolio/peripherals',
        'language' => 'und',
      ),
    ),
  );
  $terms[] = array(
    'name' => 'Floor Coverings',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '5715e047-226c-44ec-a24f-72958b91a3bd',
    'vocabulary_machine_name' => 'portfolio',
    'url_alias' => array(
      0 => array(
        'alias' => 'portfolio/floor-coverings',
        'language' => 'und',
      ),
    ),
  );
  $terms[] = array(
    'name' => 'Client Computing',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '5bf51bce-89b4-4e01-bc41-b2c9435831cd',
    'vocabulary_machine_name' => 'portfolio',
    'url_alias' => array(
      0 => array(
        'alias' => 'portfolio/client-computing',
        'language' => 'und',
      ),
    ),
  );
  $terms[] = array(
    'name' => 'Firearms',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '5c00f165-21b0-4420-9a45-03025e4f3bc8',
    'vocabulary_machine_name' => 'portfolio',
    'url_alias' => array(
      0 => array(
        'alias' => 'portfolio/firearms',
        'language' => 'und',
      ),
    ),
  );
  $terms[] = array(
    'name' => 'Training & Human Resources',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '5e34086d-1ee7-4c4c-ad8d-86571be2c0d8',
    'vocabulary_machine_name' => 'portfolio',
    'url_alias' => array(
      0 => array(
        'alias' => 'portfolio/training-human-resources',
        'language' => 'und',
      ),
    ),
  );
  $terms[] = array(
    'name' => 'US Access',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '623294e9-65dc-4e0f-b302-650ccee0c928',
    'vocabulary_machine_name' => 'portfolio',
    'url_alias' => array(
      0 => array(
        'alias' => 'portfolio/us-access',
        'language' => 'und',
      ),
    ),
  );
  $terms[] = array(
    'name' => 'Act',
    'description' => '<p>Description of Act.</p>
',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '639f8894-4c96-4018-be04-f12b8ae94b72',
    'vocabulary_machine_name' => 'interaction_mode',
    'url_alias' => array(
      0 => array(
        'alias' => 'interaction-mode/act',
        'language' => 'und',
      ),
    ),
  );
  $terms[] = array(
    'name' => 'Recreational Equipment',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '65e641e6-6a43-4966-9697-9333c1a59c8d',
    'vocabulary_machine_name' => 'portfolio',
    'url_alias' => array(
      0 => array(
        'alias' => 'portfolio/recreational-equipment',
        'language' => 'und',
      ),
    ),
  );
  $terms[] = array(
    'name' => 'Photography',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '6db197c0-1acd-4b37-820a-e87f08e573d4',
    'vocabulary_machine_name' => 'portfolio',
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'Office Supplies and Equipment',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '779cfc6e-bd47-448d-aa49-53bca658269a',
    'vocabulary_machine_name' => 'portfolio',
    'url_alias' => array(
      0 => array(
        'alias' => 'portfolio/office-supplies-and-equipment',
        'language' => 'und',
      ),
    ),
  );
  $terms[] = array(
    'name' => 'Management & Administrative Services',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '7c0a926f-ec32-4186-9314-bf23718d48cf',
    'vocabulary_machine_name' => 'portfolio',
    'url_alias' => array(
      0 => array(
        'alias' => 'portfolio/management-administrative-services',
        'language' => 'und',
      ),
    ),
  );
  $terms[] = array(
    'name' => 'Web Design',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '808c13b1-d694-4cb9-ba95-b64973d8146a',
    'vocabulary_machine_name' => 'tags',
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'Televisions',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '818633cb-14ee-4155-98e0-e19561944ac9',
    'vocabulary_machine_name' => 'portfolio',
    'url_alias' => array(
      0 => array(
        'alias' => 'portfolio/televisions',
        'language' => 'und',
      ),
    ),
  );
  $terms[] = array(
    'name' => 'Technical Services: Logistics',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '84d51801-8aa6-4500-a150-53625cda9f87',
    'vocabulary_machine_name' => 'portfolio',
    'url_alias' => array(
      0 => array(
        'alias' => 'portfolio/technical-services-logistics',
        'language' => 'und',
      ),
    ),
  );
  $terms[] = array(
    'name' => 'Illustration',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '85980d79-570c-43f3-b87e-437ef8156105',
    'vocabulary_machine_name' => 'portfolio',
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'Mobility/Wireless Services',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '86ac1518-f068-4d18-8b6e-3ebecd1dd145',
    'vocabulary_machine_name' => 'portfolio',
    'url_alias' => array(
      0 => array(
        'alias' => 'portfolio/mobilitywireless-services',
        'language' => 'und',
      ),
    ),
  );
  $terms[] = array(
    'name' => 'Self Defence',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '871378be-29f8-4ff4-ae77-e0b208ecc2d5',
    'vocabulary_machine_name' => 'portfolio',
    'url_alias' => array(
      0 => array(
        'alias' => 'portfolio/self-defence',
        'language' => 'und',
      ),
    ),
  );
  $terms[] = array(
    'name' => 'Workplace Design',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '911a6fe9-0b32-4d30-86c3-a82fcdbbaffb',
    'vocabulary_machine_name' => 'portfolio',
    'url_alias' => array(
      0 => array(
        'alias' => 'portfolio/workplace-design',
        'language' => 'und',
      ),
    ),
  );
  $terms[] = array(
    'name' => 'Systems',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '95c32512-e4f9-4191-a821-7b6daf9a5ac6',
    'vocabulary_machine_name' => 'portfolio',
    'url_alias' => array(
      0 => array(
        'alias' => 'portfolio/systems',
        'language' => 'und',
      ),
    ),
  );
  $terms[] = array(
    'name' => 'Security',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '99ac5141-4609-4f8d-afea-a2c5e801b52b',
    'vocabulary_machine_name' => 'portfolio',
    'url_alias' => array(
      0 => array(
        'alias' => 'portfolio/security',
        'language' => 'und',
      ),
    ),
  );
  $terms[] = array(
    'name' => 'Web Design',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '9cee68dc-ee49-43ca-a820-c7c7899d129e',
    'vocabulary_machine_name' => 'portfolio',
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'Temporary Administrative Services',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => '9d3c9f65-0263-497a-ba19-58071ac18551',
    'vocabulary_machine_name' => 'portfolio',
    'url_alias' => array(
      0 => array(
        'alias' => 'portfolio/temporary-administrative-services',
        'language' => 'und',
      ),
    ),
  );
  $terms[] = array(
    'name' => 'Residential Furniture',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'a38be0e1-9211-4b78-b2fe-1f557475900c',
    'vocabulary_machine_name' => 'portfolio',
    'url_alias' => array(
      0 => array(
        'alias' => 'portfolio/residential-furniture',
        'language' => 'und',
      ),
    ),
  );
  $terms[] = array(
    'name' => 'Travel',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'a4645c87-d34f-4c25-86f8-7d3603b4c9cd',
    'vocabulary_machine_name' => 'portfolio',
    'url_alias' => array(
      0 => array(
        'alias' => 'portfolio/travel',
        'language' => 'und',
      ),
    ),
  );
  $terms[] = array(
    'name' => 'Integrated Card Products',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'a6e7279e-c076-4a69-8f9a-2591b7885fe6',
    'vocabulary_machine_name' => 'portfolio',
    'url_alias' => array(
      0 => array(
        'alias' => 'portfolio/integrated-card-products',
        'language' => 'und',
      ),
    ),
  );
  $terms[] = array(
    'name' => 'Marketing & Media',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'aacd346f-8899-490c-937c-ca7523d85946',
    'vocabulary_machine_name' => 'portfolio',
    'url_alias' => array(
      0 => array(
        'alias' => 'portfolio/marketing-media',
        'language' => 'und',
      ),
    ),
  );
  $terms[] = array(
    'name' => 'Language Services',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'ab187c53-61df-41c3-82af-0270253b5234',
    'vocabulary_machine_name' => 'portfolio',
    'url_alias' => array(
      0 => array(
        'alias' => 'portfolio/language-services',
        'language' => 'und',
      ),
    ),
  );
  $terms[] = array(
    'name' => 'Transport and Data Center Services',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'ac3dda28-16c5-4360-ac04-b8fb4b23fdf1',
    'vocabulary_machine_name' => 'portfolio',
    'url_alias' => array(
      0 => array(
        'alias' => 'portfolio/transport-and-data-center-services',
        'language' => 'und',
      ),
    ),
  );
  $terms[] = array(
    'name' => 'Managed Network',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'b0b9088e-8f70-4469-9c50-bc21b49bed62',
    'vocabulary_machine_name' => 'portfolio',
    'url_alias' => array(
      0 => array(
        'alias' => 'portfolio/managed-network',
        'language' => 'und',
      ),
    ),
  );
  $terms[] = array(
    'name' => 'GSA Fleet Services',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'b247738c-a1af-4b5e-857f-d4b99b468c23',
    'vocabulary_machine_name' => 'portfolio',
    'url_alias' => array(
      0 => array(
        'alias' => 'portfolio/gsa-fleet-services',
        'language' => 'und',
      ),
    ),
  );
  $terms[] = array(
    'name' => 'Industrial Products',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'b33ea66c-607d-4059-b86f-f2013e45e3fb',
    'vocabulary_machine_name' => 'portfolio',
    'url_alias' => array(
      0 => array(
        'alias' => 'portfolio/industrial-products',
        'language' => 'und',
      ),
    ),
  );
  $terms[] = array(
    'name' => 'Lodging',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'b8893636-bbeb-43f6-a653-a6b697d81ed4',
    'vocabulary_machine_name' => 'portfolio',
    'url_alias' => array(
      0 => array(
        'alias' => 'portfolio/lodging',
        'language' => 'und',
      ),
    ),
  );
  $terms[] = array(
    'name' => 'administrative',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'c699b677-7a91-4ccb-b507-a01120d0b3b2',
    'vocabulary_machine_name' => 'tags',
    'url_alias' => array(
      0 => array(
        'alias' => 'tags/administrative',
        'language' => 'und',
      ),
    ),
  );
  $terms[] = array(
    'name' => 'Dormitory',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'c8f2700d-1d55-4a8e-9f10-b202e387b455',
    'vocabulary_machine_name' => 'portfolio',
    'url_alias' => array(
      0 => array(
        'alias' => 'portfolio/dormitory',
        'language' => 'und',
      ),
    ),
  );
  $terms[] = array(
    'name' => 'Travel Booking Channel Management',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'cd24a772-cedc-4bf4-b77e-769f7d83d106',
    'vocabulary_machine_name' => 'portfolio',
    'url_alias' => array(
      0 => array(
        'alias' => 'portfolio/travel-booking-channel-management',
        'language' => 'und',
      ),
    ),
  );
  $terms[] = array(
    'name' => 'Storage',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'cde36a4e-bb09-448d-9792-77a508531e90',
    'vocabulary_machine_name' => 'portfolio',
    'url_alias' => array(
      0 => array(
        'alias' => 'portfolio/storage',
        'language' => 'und',
      ),
    ),
  );
  $terms[] = array(
    'name' => 'Services',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'dc247bc7-169e-48b6-8386-c9b148411ff3',
    'vocabulary_machine_name' => 'portfolio',
    'url_alias' => array(
      0 => array(
        'alias' => 'portfolio/services',
        'language' => 'und',
      ),
    ),
  );
  $terms[] = array(
    'name' => 'Human Resources and Training Services',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'dc7a274f-3343-42c7-b7da-f9380973ed41',
    'vocabulary_machine_name' => 'tags',
    'url_alias' => array(
      0 => array(
        'alias' => 'tags/human-resources-and-training-services',
        'language' => 'und',
      ),
    ),
  );
  $terms[] = array(
    'name' => 'Temporary Services',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'dcac6e4b-b17b-4bcb-a7e1-c69d63b71d7f',
    'vocabulary_machine_name' => 'portfolio',
    'url_alias' => array(
      0 => array(
        'alias' => 'portfolio/temporary-services',
        'language' => 'und',
      ),
    ),
  );
  $terms[] = array(
    'name' => 'Connect',
    'description' => '<p>Description of&nbsp;Connect.</p>
',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'e0ea8a9c-07dd-4257-aaf8-7f1e4348573b',
    'vocabulary_machine_name' => 'interaction_mode',
    'url_alias' => array(
      0 => array(
        'alias' => 'interaction-mode/connect',
        'language' => 'und',
      ),
    ),
  );
  $terms[] = array(
    'name' => 'Facilities Management',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'e1c9552c-eedd-4d25-b457-e237b7717155',
    'vocabulary_machine_name' => 'portfolio',
    'url_alias' => array(
      0 => array(
        'alias' => 'portfolio/facilities-management',
        'language' => 'und',
      ),
    ),
  );
  $terms[] = array(
    'name' => 'Equipment',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'e243c7ca-22db-41d1-b45d-a58eddefaae2',
    'vocabulary_machine_name' => 'portfolio',
    'url_alias' => array(
      0 => array(
        'alias' => 'portfolio/equipment',
        'language' => 'und',
      ),
    ),
  );
  $terms[] = array(
    'name' => 'administrative support',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'e7c6f023-edd9-4757-ae38-cd2957721322',
    'vocabulary_machine_name' => 'tags',
    'url_alias' => array(
      0 => array(
        'alias' => 'tags/administrative-support',
        'language' => 'und',
      ),
    ),
  );
  $terms[] = array(
    'name' => 'Installation',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'eb1b3fb6-4a46-4925-ab33-9395d6f2a94c',
    'vocabulary_machine_name' => 'portfolio',
    'url_alias' => array(
      0 => array(
        'alias' => 'portfolio/installation',
        'language' => 'und',
      ),
    ),
  );
  $terms[] = array(
    'name' => 'Concept Services',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'ec1032d9-d6f5-4061-a22f-1fd5f6ec40e1',
    'vocabulary_machine_name' => 'portfolio',
    'url_alias' => array(
      0 => array(
        'alias' => 'portfolio/concept-services',
        'language' => 'und',
      ),
    ),
  );
  $terms[] = array(
    'name' => 'Barracks',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'f11b2409-c73b-4206-9790-910057f3367e',
    'vocabulary_machine_name' => 'portfolio',
    'url_alias' => array(
      0 => array(
        'alias' => 'portfolio/barracks',
        'language' => 'und',
      ),
    ),
  );
  $terms[] = array(
    'name' => 'Travel Training',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'f339e4a3-1800-4b08-bbce-b144c3553cd2',
    'vocabulary_machine_name' => 'portfolio',
    'url_alias' => array(
      0 => array(
        'alias' => 'portfolio/travel-training',
        'language' => 'und',
      ),
    ),
  );
  $terms[] = array(
    'name' => 'Enterprise Application Software',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'f695c424-99ab-43b7-86a2-f30447f7ab6c',
    'vocabulary_machine_name' => 'portfolio',
    'url_alias' => array(
      0 => array(
        'alias' => 'portfolio/enterprise-application-software',
        'language' => 'und',
      ),
    ),
  );
  $terms[] = array(
    'name' => 'Purchase',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'fa92f997-09d7-4174-9f55-de2f6f549463',
    'vocabulary_machine_name' => 'portfolio',
    'url_alias' => array(
      0 => array(
        'alias' => 'portfolio/purchase',
        'language' => 'und',
      ),
    ),
  );
  $terms[] = array(
    'name' => 'Financial Management Services',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'fcb5188d-0225-4cf8-bfea-a961c815e6b9',
    'vocabulary_machine_name' => 'portfolio',
    'url_alias' => array(
      0 => array(
        'alias' => 'portfolio/financial-management-services',
        'language' => 'und',
      ),
    ),
  );
  return $terms;
}
