<?php
/**
 * @file
 * hallways_articles_views_and_blocks.features.fe_block_settings.inc
 */

/**
 * Implements hook_default_fe_block_settings().
 */
function hallways_articles_views_and_blocks_default_fe_block_settings() {
  $export = array();

  $export['version'] = '2.0';

  $export['views-1b98e4e87d58eaeabd586dabd61bdf36'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => '1b98e4e87d58eaeabd586dabd61bdf36',
    'module' => 'views',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'bootstrap' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bootstrap',
        'weight' => 0,
      ),
      'other_sub' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'other_sub',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['views-246fb6d1ef57fba541875e03b253d0fb'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => '246fb6d1ef57fba541875e03b253d0fb',
    'module' => 'views',
    'node_types' => array(),
    'pages' => 'admin/sorting-it-software',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'bootstrap' => array(
        'region' => 'content',
        'status' => 1,
        'theme' => 'bootstrap',
        'weight' => -45,
      ),
      'other_sub' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'other_sub',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 1,
  );

  $export['views-5c48744a2acc85fc6518c357f7a2bf5a'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => '5c48744a2acc85fc6518c357f7a2bf5a',
    'module' => 'views',
    'node_types' => array(),
    'pages' => 'AdministrativeSupport',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'bootstrap' => array(
        'region' => 'content_bottom',
        'status' => 1,
        'theme' => 'bootstrap',
        'weight' => -56,
      ),
      'other_sub' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'other_sub',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => '<none>',
    'visibility' => 1,
  );

  $export['views-6995fe9992e01ad97ec3e6686a05d9c1'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => '6995fe9992e01ad97ec3e6686a05d9c1',
    'module' => 'views',
    'node_types' => array(),
    'pages' => 'ITSoftware',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'bootstrap' => array(
        'region' => 'content_bottom',
        'status' => 1,
        'theme' => 'bootstrap',
        'weight' => -56,
      ),
      'other_sub' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'other_sub',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => '<none>',
    'visibility' => 1,
  );

  $export['views-7275a366f383bbfb14cd482360480226'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => '7275a366f383bbfb14cd482360480226',
    'module' => 'views',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'bootstrap' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bootstrap',
        'weight' => 0,
      ),
      'other_sub' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'other_sub',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['views-7370b344d1494e2ee277189bb1de8246'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => '7370b344d1494e2ee277189bb1de8246',
    'module' => 'views',
    'node_types' => array(),
    'pages' => 'admin/sorting-it-hardware',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'bootstrap' => array(
        'region' => 'content',
        'status' => 1,
        'theme' => 'bootstrap',
        'weight' => -46,
      ),
      'other_sub' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'other_sub',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['views-ca6987b323c228df1a01d314ca9064d3'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'ca6987b323c228df1a01d314ca9064d3',
    'module' => 'views',
    'node_types' => array(),
    'pages' => 'ITHardware',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'bootstrap' => array(
        'region' => 'content_bottom',
        'status' => 1,
        'theme' => 'bootstrap',
        'weight' => -56,
      ),
      'other_sub' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'other_sub',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => '<none>',
    'visibility' => 1,
  );

  $export['views-d5661c6d85890a1dc9a769c7076129f3'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'd5661c6d85890a1dc9a769c7076129f3',
    'module' => 'views',
    'node_types' => array(),
    'pages' => 'admin/sorting-administrative-support',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'bootstrap' => array(
        'region' => 'content',
        'status' => 1,
        'theme' => 'bootstrap',
        'weight' => -47,
      ),
      'other_sub' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'other_sub',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  return $export;
}
